apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-cufesybf
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-cufesybf:3d3a05e5dcefd57000ab3398f2b5fd8771c406d4@sha256:291a9bbeca88cf5b6ed569df822b61bc77a878010b15d26b4d966e4c854e08e2
          name: container-image
